Add hw4 checkio task solutions
MrDunn0/BI_2019_Python pull request #5
Opened 2019-10-29 17:32 UTC by MrDunn0

Есть ощущение, что в последних 2-х задачах очень много всего лишнего...

2019-10-31 19:14 UTC, AleksandrSl requested changes

2019-10-31 19:14 UTC, AleksandrSl commented on HW4_checkio/common_words.py
> +    return ",".join(result)
Тут сложность - n^2, можно n. Плюс питон скорее всего не сообразит соптимизировать и будет `str2.split(",")` делать на каждой итерации

2019-10-31 19:14 UTC, AleksandrSl commented on HW4_checkio/group_equal_consequtive.py
> +def group_equal(list_to_group, prefix=[]):  # Pycharm ноет, но Артем так учил...
Так, сигнатуру функции, трогать нельзя. Пустые списки класть в значения по умолчанию для этого вообще отдельный котел в Аду, надеюсь ты просто неправильно понял Артема

2019-10-31 19:14 UTC, AleksandrSl commented on HW4_checkio/group_equal_consequtive.py
> +            return group_equal(list_to_group[i + 1:], prefix + [equal_consecutive])
Рекурсивность это конечно неплохо, но здесь она мало того что неэффективная по всем параметрам, так еще и длинее нерекурсивного решения раза в полтора

2019-10-31 19:14 UTC, AleksandrSl commented on HW4_checkio/group_equal_consequtive.py
> +    for i in range(len(list_to_group)):
Кажется, что должно работать как минимум также
```
    for i in range(len(list_to_group) - 1):
        equal_consecutive.append(list_to_group[i])
        if list_to_group[i] != list_to_group[i + 1]:
            result.append([equal for equal in equal_consecutive])
            equal_consecutive.clear()
    result.append([equal for equal in equal_consecutive])
```

2019-10-31 19:14 UTC, AleksandrSl commented on HW4_checkio/intervals.py
> +    sorted_set_of_ints = sorted(list(set_of_ints))
Тут можно опустить list, см определение `sorted`

2019-10-31 19:41 UTC, MrDunn0 commented on HW4_checkio/group_equal_consequtive.py
> +    for i in range(len(list_to_group)):
Я мб чет не понял, но у меня в таком случае получается, что последний элемент не включается.

2019-11-01 18:59 UTC, AleksandrSl commented on HW4_checkio/group_equal_consequtive.py
> +    for i in range(len(list_to_group)):
Да, справделиво, это конечно чинится, но не сильно веселее код выходит

2019-11-01 19:08 UTC, AleksandrSl commented on HW4_checkio/group_equal_consequtive.py
> +            equal_consecutive.clear()
Но это вот сто процентов) Если здесь делать не `clear` , а `equal_consecutive = []`, то можно просто делать `result.append(equal_consecutive)`. Так как в таком случае у тебя старые списки остаются где надо, а набирать новые элементы ты начинаешь в новый список.
И даже если ты хочешь делать clear копировать списки можно проще, либо `some_list[:]` либо есть функция `copy`

2019-11-02 10:31 UTC, MrDunn0 commented
Я оставил рекурсивную функцию, чтобы она в истории осталась, а то я столько времени на нее потратил)) Вроде остальное все учел. В задаче с общими словами же при использовании словаря время O(n) получается?

2019-11-02 10:38 UTC, MrDunn0 commented
Теперь вроде все...

2019-11-02 19:15 UTC, AleksandrSl commented on HW4_checkio/common_words.py
> +    dict_with_str_1_words = {word for word in str_1_words}
Достаточно `set(str_1_words)`

2019-11-02 19:15 UTC, AleksandrSl commented on HW4_checkio/group_equal_consequtive.py
> +            equal_consecutive = []
Раз ты тут теперь новый список создаешь, то не надо делать копии, то есть `[:]` можно убирать

2019-11-02 21:08 UTC, MrDunn0 commented
Ну теперь-то уж точно все...

2020-01-03 00:21 UTC, merged